ENV['VAGRANT_NO_PARALLEL'] = 'yes'
cluster_name = "c1"
ip_segment = "192.168.50.21"
ip_index=1
Vagrant.configure(2) do |config|

  config.vm.define "#{cluster_name}-master01" do |node|
    node.vm.box               = "generic/debian12"
    node.vm.box_check_update  = false
    node.vm.hostname          = "master01.kubernetes.cluster"
    node.vm.network "public_network", ip: "#{ip_segment}#{ip_index}"
    ip_index+=1
    node.vm.provider :virtualbox do |v|
      v.name    = "#{cluster_name}-master01"
      v.memory  = 2048
      v.cpus    = 4
    end
    node.vm.provider :libvirt do |v|
      v.memory  = 2048
      v.nested  = true
      v.cpus    = 2
    end

    node.vm.provision "shell", path: "bootstrap.sh", args: "master #{ip_segment}"
  end
  (1..1).each do |i|
    config.vm.define "#{cluster_name}-worker0#{i}" do |node|
      node.vm.box               = "generic/debian12"
      node.vm.box_check_update  = false
      node.vm.hostname          = "worker0#{i}.kubernetes.cluster"
      node.vm.network "private_network", ip: "#{ip_segment}#{ip_index}"
      ip_index+=1
      node.vm.provider :virtualbox do |v|
        v.name    = "#{cluster_name}-worker0#{i}"
        v.memory  = 1024
        v.cpus    = 1
      end
      node.vm.provider :libvirt do |v|
        v.memory  = 1024
        v.nested  = true
        v.cpus    = 2
      end
      node.vm.provision "shell", path: "bootstrap.sh", args: "worker #{ip_segment}"
    end
  end
end
